[versions]

fabric-loader = "0.16.10"
fabric-language-kotlin = "1.13.4+kotlin.2.2.0"
fabric-api = "0.133.4"

kotlin = "2.2.0"
kotlin-symbol-processor = "2.2.0-2.0.2"
gson = "2.12.1"
skyblockapi = "3.0.24"
skyblockapi-repo = "3.0.2"
placeholders = "2.6.1+1.21.5"
keval = "1.1.1"

rconfigkt = "3.5.15"

detekt = "2.0.0-alpha.0"

meowdding-lib = "3.1.1"
meowdding-ktmodules = "1.0.6"
meowdding-ktcodecs = "1.1.5"
meowdding-gradle = "1.1.0"
meowdding-remote-repo = "1.0.4"
meowdding-resources = "1.0.17"
meowdding-auto-mixins = "1.0.7"

terrarium-cloche = "0.13.5"

[libraries]

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

skyblockapi = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblockapi" }
skyblockapi-repo = { module = "tech.thatgravyboat.repo-lib:repo-lib", version.ref = "skyblockapi-repo" }
placeholders = { module = "eu.pb4:placeholder-api", version.ref = "placeholders" }
keval = { module = "com.notkamui.libs:keval", version.ref = "keval" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

resourceful-config-kotlin = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-fabric-1.21.5", version.ref = "rconfigkt" }

meowdding-lib = { module = "me.owdding.meowdding-lib:meowdding-lib", version.ref = "meowdding-lib" }
meowdding-remote-repo = { module = "me.owdding.repo:remote-repo", version.ref = "meowdding-remote-repo" }
meowdding-ktmodules = { module = "me.owdding.ktmodules:KtModules", version.ref = "meowdding-ktmodules" }
meowdding-ktcodecs = { module = "me.owdding.ktcodecs:KtCodecs", version.ref = "meowdding-ktcodecs" }
meowdding-resources = { module = "me.owdding.repo:compacting-resources", version.ref = "meowdding-resources" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

detekt-plugin = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-ktlintWrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }

[plugins]
meowdding-auto-mixins = { id = "me.owdding.auto-mixins", version.ref = "meowdding-auto-mixins" }
meowdding-resources = { id = "me.owdding.resources" }

kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-symbol-processor = { id = "com.google.devtools.ksp", version.ref = "kotlin-symbol-processor" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
