[versions]

fabric-loader = "0.18.3"
fabric-language-kotlin = "1.13.6+kotlin.2.2.20"
fabric-api = "0.133.4"

kotlin-symbol-processor = "2.2.0-2.0.2"
gson = "2.12.1"
skyblockapi = "4.0.7"
skyblockapi-repo = "3.0.2"
keval = "1.1.1"

hypixel-modapi-fabric = "1.0.1+build.1+mc1.21"

rconfigkt = "3.5.15"

detekt = "2.0.0-alpha.0"

meowdding-lib = "4.0.4"
meowdding-ktmodules = "1.0.6"
meowdding-ktcodecs = "1.1.5"
meowdding-resources = "1.0.21"
meowdding-auto-mixins = "1.0.7"

moulberry-mixinconstraints = "1.0.8"

[libraries]

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

skyblockapi = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblockapi" }
skyblockapi-repo = { module = "tech.thatgravyboat.repo-lib:repo-lib", version.ref = "skyblockapi-repo" }
keval = { module = "com.notkamui.libs:keval", version.ref = "keval" }

hypixel-modapi-fabric = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixel-modapi-fabric" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

resourceful-config-kotlin = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-fabric-1.21.5", version.ref = "rconfigkt" }

meowdding-lib = { module = "me.owdding.meowdding-lib:meowdding-lib", version.ref = "meowdding-lib" }
meowdding-ktmodules = { module = "me.owdding.ktmodules:KtModules", version.ref = "meowdding-ktmodules" }
meowdding-ktcodecs = { module = "me.owdding.ktcodecs:KtCodecs", version.ref = "meowdding-ktcodecs" }
meowdding-resources = { module = "me.owdding.repo:compacting-resources", version.ref = "meowdding-resources" }

moulberry-mixinconstraints = { module = "com.moulberry:mixinconstraints", version.ref = "moulberry-mixinconstraints" }

detekt-ktlintWrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }

[plugins]
meowdding-auto-mixins = { id = "me.owdding.auto-mixins", version.ref = "meowdding-auto-mixins" }
meowdding-resources = { id = "me.owdding.resources" }

kotlin-symbol-processor = { id = "com.google.devtools.ksp", version.ref = "kotlin-symbol-processor" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
